### ISSUE TITLE
[열차변경] 신칸센 500계 Cool 

### ISSUE THREAD

**Issue by Pokerface-YUTHMAIN** [MEGB-NewGRF/VirtualTrainSet#11]
==========[필수스프라이트]==========
기본스프라이트

==========[32bpp스프라이트]==========

![500 Cool](https://user-images.githubusercontent.com/101701121/176838939-549edace-f9cc-4829-9c45-970e89bcf67a.png)

==========[설명]==========

==========[YST적용내용]==========
적용될 기존 열차 이름 : Shinkansen 500 Cool 
도색 추가시 열차 이름 :

**Comment by evepoi** [comment]
신규 Cool 도색
![Shinkansen_500_Cool2_32bpp](https://user-images.githubusercontent.com/55119879/177023346-5876a3d3-d306-4e87-8dab-540407f58cbc.png)
어떠신가요?
