### ISSUE TITLE
[열차추가] 한국형 레일젯

### ISSUE THREAD

**Issue by JukjeonWani** [MEGB-NewGRF/VirtualTrainSet#14]
==========[필수스프라이트]==========
![KE_RJET](https://user-images.githubusercontent.com/88026704/187068377-f3c35a74-1f8e-40d2-bb3d-b05576efc97d.png)

==========[설명]==========
안뒤집히는걸 의도했기 때문에 후미 스프라이트가 없고 양쪽 모두 전조등 점등 상태입니다.

==========[YST적용내용]==========
GRF내 열차 이름 : KO RAIL JET
열차속도 : 150
도입년도 : 2030
객차당 수송량 : 200명

**Comment by evepoi** [comment]
#16 의 개선으로 적용합니다.
