### ISSUE TITLE
[열차추가] CTX

### ISSUE THREAD

**Issue by EightonEight** [MEGB-NewGRF/VirtualTrainSet#21]
#### ==========[필수스프라이트]==========
![CTX_FC_R](https://user-images.githubusercontent.com/77984422/192987026-96c92aec-7116-4081-a358-76f305673d67.png)
`CTX_FC_R` (Freight Car)

![CTX_HC_R](https://user-images.githubusercontent.com/77984422/192987498-efad4ea7-8302-47a6-bb6d-1427f0bfec63.png)
`CTX_HC_R` (passenger/freight Hybrid Car)

#### ==========[설명]==========
과거 연구되었던 CTX(Cargo Train eXpress, 고속화물열차)와 Hy-SoBex(Hybrid-Surface optimal Baggage express, 여객/화물 고속복합열차)입니다.

공개된 실차는 없기에 가상열차세트로 추가합니다.

**References:**
* 고속화물열차 제원
  - 한국철도기술연구원, 「차량편성구성에 따른 고속화물열차의 추진 및 제동성능 분석 연구」, 2016
* 여객/화물 고속복합열차 제원
  - 한국철도공사, 「여객/화물 고속복합열차를 이용한 소화물 운송 최적 서비스 모델 연구」, 2014
* 도색 디자인 참고
  - 한국철도공사, 「고속차량 KTX-산천 디자인의미 소개」, 2012

#### ==========[적용내용]==========
**GRF내 열차 이름 :** CTX / CTX
**도색 이름 :** 
* CTX 화물전용 와인도색  /  CTX Freight Only Wine Livery
* CTX 여객-화물복합 와인도색 / CTX Passenger-Freight Wine Livery

**열차속도 :** 300km/h (한국열차세트 KTX-산천과 동일)
**도입년도 :** 2020
**수송량 :** 화물 20t (개조 가능)
실제 수송량은 15t 정도이나, 게임상 편의를 위해 20t으로 설정하였습니다.
**출력 :** 8800kW
**중량 :** 136t
**최소 편성수 :** 기관차 포함 4량
**편성 조성 방법 :**
```
4량: PC1 - T1 - T4 - PC2 
5량: PC1 - T1 - T2 - T4 - PC2 
6량: PC1 - T1 - T2 - T3 - T4 - PC2 
7량~: PC1 - T1 - T2 - ⋯ -  T2 - T3 - ⋯ - T3 - T4 - PC2 
```
**실존여부 :** X (연구단계)

OpenTTD 게임 특성 상 한 차량에 승객과 화물을 동시에 실을 수 없으므로, 스프라이트 상으로만 여객/화물 복합열차를 구현하고  게임 내에서는 화물만 싣게 하면 좋을 것 같습니다.

**Comment by JukjeonWani** [comment]
최고속도는 가상셋과 KTS+의 300km/h대 고속열차에 맞게 331km/h로 반영하는 것이 어떨까요?

**Comment by evepoi** [comment]
> 최고속도는 가상셋과 KTS+의 300km/h대 고속열차에 맞게 331km/h로 반영하는 것이 어떨까요?

매개변수로 적용하게 될 예정입니다

**Comment by evepoi** [comment]
구현상 승객과 화물등이 쉽지 않습니다.
TTD특성이 그래서 어쩔수 없죠 ㅠ

하여 여객화물복합은 신중히 결정하겠습니다

**Comment by EightonEight** [comment]
> 구현상 승객과 화물등이 쉽지 않습니다. TTD특성이 그래서 어쩔수 없죠 ㅠ
> 
> 하여 여객화물복합은 신중히 결정하겠습니다

설명에 T1과 T4 차량은 여객/화물 복합열차 스프라이트로 하되, 실제로는 화물만 싣게한다는 것을 누락했네요...

**Comment by JukjeonWani** [comment]
T1, T4의 화물수송량은 PC에 배정하고 승객수송량을 T1, T4에 배정하는 방법도 있을 듯 합니다

**Comment by EightonEight** [comment]
[MEGB-NewGRF/KoreanTrainSet_Plus#46](https://github.com/MEGB-NewGRF/KoreanTrainSet_Plus/issues/46)로 이관합니다.
